config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cheer.rb
class Cheer < ApplicationRecord
    validates :user_id, :goal_id, presence: true

    belongs_to :user,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :User

    belongs_to :goal
end

app/models/goal.rb
class Goal < ApplicationRecord
    validates :title, :visibility, :is_finished, :user_id, presence: true

    has_many :cheers,
        primary_key: :id,
        foreign_key: :goal_id,
        class_name: :Cheer

    belongs_to :user,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :User
end

app/models/user.rb
class User < ApplicationRecord
    attr_reader :password

    validates :username, :session_token, :password_digest, presence: true
    validates :username, :session_token, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        user && user.is_password?(password) ? user : nil 
    end
    
    has_many :goals,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :Goal

    has_many :cheers,
        primary_key: :id,
        foreign_key: :user_id,
        class_name: :Cheer

    def ensure_session_token
        self.session_token ||= SecureRandom.urlsafe_base64(16)
    end
    
    def reset_session_token
        self.session_token = SecureRandom.urlsafe_base64(16)
        self.save!
        self.session_token
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        render :new
    end

    def create
        user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if user
            # login!(user)
            redirect_to user_url(user)
        else 
            flash[:errors] = "Invalid credentials"
            # redirect_to new_session_url
            render :new
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])

        if @user
            render :show
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def auth_token
        html = "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\""
        html.html_safe
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>GOALING APP</h1>

    <header>
      <%# if logged_in? %>
        <form action="<%= session_url %>" value="post">
          <input type="hidden" name="_method" value="delete">
          <%= auth_token %>
          <input type="submit" value="Log Out">
        </form>

    </header>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form action="<%= users_url %>" method="post">
    <%= auth_token %>
    <label for="username">Username:</label>
    <input type="text" id="username" name="user[username]" value="">

    <label for="password">Password:</label>
    <input type="password" name="user[password]" id="password" value="">

    <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1><%=@user.username%></h1>